### ISSUE TITLE
[EPIC] JSON-RPC Gateway launch implementation

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-evm-gateway#12]
Master issue for tracking completion state of both the JSON-RPC endpoints and the issues we're using to track those sub-items. 

```[tasklist]
### API Endpoints P1 (Need for launch of development version of EVM on Flow)
- [x] eth_chainId // returns the chainID
- [x] eth_blockNumber // returns the latest block number
- [x] eth_syncing // return false for now
- [x] eth_coinbase // return the coinbase for a block
- [x] eth_getUncleCountByBlockHash // return 0
- [x] eth_getUncleCountByBlockNumber // return 0
- [x] eth_getLogs
- [x] eth_getTransactionCount // returns the number of tx sent from an address (nonce)
- [x] eth_getTransactionReceipt
- [x] eth_getBlockByNumber
- [x] eth_call
- [x] eth_sendRawTransaction
- [x] eth_getTransactionByHash
- [x] eth_gasPrice // returns the gas price
- [x] eth_getBalance //returns the balance for any given block
- [x] eth_estimateGas // usually runs the call and checks how much gas might be used
```

```[tasklist]
### API Endpoints P2
- [x] eth_getCode // returns the code for the given address
- [x] eth_getTransactionByBlockNumberAndIndex
- [x] eth_getTransactionByBlockHashAndIndex
- [x] eth_getBlockByHash
- [x] eth_getBlockReceipts
- [x] eth_getBlockTransactionCountByHash
- [x] eth_getBlockTransactionCountByNumber
- [ ] eth_createAccessList
- [ ] eth_feeHistory // transaction fee history
- [ ] eth_maxPriorityFeePerGas
- [ ] eth_getProof // returns state proof for an account
- [ ] eth_getStorageAt // we probably won't support this day 1
- [ ] eth_newFilter
- [ ] eth_uninstallFilter
- [ ] eth_getFilterLogs
- [ ] eth_getFilterChanges
- [ ] eth_newBlockFilter
- [ ] eth_newPendingTransactionFilter
- [ ] eth_accounts
- [ ] eth_sign
- [ ] eth_signTransaction
- [ ] eth_sendTransaction
```

```[tasklist]
### Implementation issues
- [x] https://github.com/onflow/flow-evm-gateway/issues/1
- [ ] https://github.com/onflow/flow-evm-gateway/issues/20
- [ ] https://github.com/onflow/flow-evm-gateway/issues/2
- [ ] https://github.com/onflow/flow-evm-gateway/issues/14
- [ ] https://github.com/onflow/flow-evm-gateway/issues/3
- [ ] https://github.com/onflow/flow-evm-gateway/issues/4
- [ ] https://github.com/onflow/flow-evm-gateway/issues/5
- [ ] https://github.com/onflow/flow-evm-gateway/issues/6
- [ ] https://github.com/onflow/flow-evm-gateway/issues/8
- [ ] https://github.com/onflow/flow-evm-gateway/issues/9
- [ ] https://github.com/onflow/flow-evm-gateway/issues/13
- [ ] https://github.com/onflow/flow-evm-gateway/pull/76
```

**Comment by j1010001** [comment]
completed and superseded by https://github.com/onflow/flow-evm-gateway/issues/126
