### ISSUE TITLE
[EPIC] Production Stable Gateway

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#126]
This epic contains all the work that is needed to make EVM Gateway production stable code, with good tests, benchmarking and general reliability, as well as security hardening. 

The remaining work is divided into multiple sub-lists. 
1. Data Streaming sub-list covers all the tasks that are needed for the streaming of events and blocks to the clients over websockets.
2. API Completeness ensures we support all the APIs needed to comply with the JSON RPC API specification. 
3. Security and testing makes sure we have implemented metrics, do sufficient benchmarking, implement validation and security checks as well as allow secure running of the gateway in production

```[tasklist]
### Data Streaming
- [ ] https://github.com/onflow/flow-evm-gateway/issues/7
- [ ] https://github.com/onflow/flow-evm-gateway/issues/127
- [ ] https://github.com/onflow/flow-evm-gateway/issues/142
- [ ] https://github.com/onflow/flow-evm-gateway/issues/141
- [ ] https://github.com/onflow/flow-evm-gateway/issues/140
- [ ] https://github.com/onflow/flow-evm-gateway/issues/139
- [ ] https://github.com/onflow/flow-evm-gateway/issues/163
- [ ] https://github.com/onflow/flow-evm-gateway/issues/164
- [ ] https://github.com/onflow/flow-evm-gateway/issues/172
```

```[tasklist]
### API Completeness
- [ ] https://github.com/onflow/flow-evm-gateway/issues/144
- [ ] https://github.com/onflow/flow-evm-gateway/issues/209
- [ ] https://github.com/onflow/flow-evm-gateway/issues/302
- [ ] https://github.com/onflow/flow-evm-gateway/issues/296
- [ ] https://github.com/onflow/flow-evm-gateway/issues/143
- [ ] https://github.com/onflow/flow-evm-gateway/issues/200
- [ ] https://github.com/onflow/flow-evm-gateway/issues/145
- [ ] https://github.com/onflow/flow-evm-gateway/issues/111
- [ ] https://github.com/onflow/flow-evm-gateway/issues/212
- [ ] https://github.com/onflow/flow-evm-gateway/issues/214
- [ ] https://github.com/onflow/flow-evm-gateway/issues/187
- [ ] https://github.com/onflow/flow-evm-gateway/issues/208
- [ ] https://github.com/onflow/flow-evm-gateway/issues/80
- [ ] https://github.com/onflow/flow-evm-gateway/issues/199
- [ ] https://github.com/onflow/flow-evm-gateway/issues/188
- [ ] https://github.com/onflow/flow-evm-gateway/issues/87
- [ ] https://github.com/onflow/flow-evm-gateway/issues/161
- [ ] https://github.com/onflow/flow-evm-gateway/issues/83
- [ ] https://github.com/onflow/flow-evm-gateway/issues/160
- [ ] https://github.com/onflow/flow-evm-gateway/issues/159
- [ ] https://github.com/onflow/flow-evm-gateway/issues/112
- [ ] https://github.com/onflow/flow-evm-gateway/issues/115
- [ ] https://github.com/onflow/flow-evm-gateway/issues/113
- [ ] https://github.com/onflow/flow-evm-gateway/issues/109
```

```[tasklist]
### Security and Stability
- [ ] https://github.com/onflow/flow-evm-gateway/issues/125
- [ ] https://github.com/onflow/flow-evm-gateway/issues/19
- [ ] https://github.com/onflow/flow-evm-gateway/issues/169
- [ ] https://github.com/onflow/flow-evm-gateway/issues/278
- [ ] https://github.com/onflow/flow-evm-gateway/issues/117
- [ ] https://github.com/onflow/flow-evm-gateway/issues/193
- [ ] https://github.com/onflow/flow-evm-gateway/issues/250
- [ ] https://github.com/onflow/flow-evm-gateway/issues/211
- [ ] https://github.com/onflow/flow-evm-gateway/issues/101
- [ ] https://github.com/onflow/flow-evm-gateway/issues/236
- [ ] https://github.com/onflow/flow-evm-gateway/issues/204
- [ ] https://github.com/onflow/flow-evm-gateway/issues/82
- [ ] https://github.com/onflow/flow-evm-gateway/issues/116
- [ ] https://github.com/onflow/flow-evm-gateway/issues/85
- [ ] https://github.com/onflow/flow-evm-gateway/issues/122
- [ ] https://github.com/onflow/flow-evm-gateway/issues/123
- [ ] https://github.com/onflow/flow-evm-gateway/issues/119
- [ ] https://github.com/onflow/flow-evm-gateway/issues/183
- [ ] https://github.com/onflow/flow-evm-gateway/issues/197
```

**Comment by j1010001** [comment]
Remaining issue is benchmarking - keeping that separate, closing the EPIC
