### ISSUE TITLE
[EPIC] Indexer Implementation

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#14]
A module must be implemented to index the EVM-related data in local storage. Having an index of such data will allow for querying this data through the grpc API described here: #12 

Such a module would have to rely on Flow events to monitor the EVM execution and extrapolate relevant data out of two relevant EVM events:
- Transaction execution event: `evm.TransactionExecuted` 
- Block execution event: `evm.BlockExecuted`

The requirements for the indexer are:
- persistence of the data index
- indexing the event data in sequence without skipping any of the events 
- index the data in real-time, not falling behind the execution
- allow for multiple concurrent query requests and allow for scaling to thousands of requests per second

Implementation will be broken into multiple tasks, defined bellow:

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-evm-gateway/issues/15
- [ ] https://github.com/onflow/flow-evm-gateway/issues/16
- [ ] https://github.com/onflow/flow-evm-gateway/issues/17
- [ ] https://github.com/onflow/flow-evm-gateway/issues/18
- [ ] https://github.com/onflow/flow-evm-gateway/issues/19
- [ ] https://github.com/onflow/flow-evm-gateway/issues/28
- [ ] https://github.com/onflow/flow-evm-gateway/issues/38
- [ ] https://github.com/onflow/flow-evm-gateway/issues/49
- [ ] https://github.com/onflow/flow-evm-gateway/issues/56
- [ ] https://github.com/onflow/flow-evm-gateway/issues/57
- [ ] https://github.com/onflow/flow-evm-gateway/issues/58
- [ ] https://github.com/onflow/flow-evm-gateway/issues/59
```

**Comment by j1010001** [comment]
superseded by https://github.com/onflow/flow-evm-gateway/issues/126
