### ISSUE TITLE
Add support for debug_traceCall to EVM GW API

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-evm-gateway#530]
This endpoint is required for ERC-4337 integration 

https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtracecall

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-evm-gateway/issues/641
- [ ] https://github.com/onflow/flow-evm-gateway/issues/642
- [ ] https://github.com/onflow/flow-evm-gateway/issues/643
```

**Comment by SeanRobb** [comment]
@franklywatson @sideninja 

Can we get it estimated and prioritized as it is blocking Alchemy ERC-4337 bundler. Which then is blocking 2 integration P1 partners for us?

**Comment by sideninja** [comment]
@SeanRobb what is the expected tracer configuration they will want to use? the same one as we currently support for trace transaction?

**Comment by SeanRobb** [comment]
@franklywatson @AnukeG do we have an answer for @sideninja question?

**Comment by dancoombs** [comment]
By tracer config are you referring to the Geth [`TraceConfig`](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#traceconfig)?

If so, we currently use `tracer` with a javascript tracer, and `timeout`.

Our usage is here (Rust): https://github.com/alchemyplatform/rundler/blob/7b5097f537b25b504951584df6f3bc18fdb29d68/crates/sim/src/simulation/v0_7/tracer.rs#L155

**Comment by franklywatson** [comment]
FYI this needs to include state_overrides to meet ERC-4337 integration requirements

**Comment by m-Peter** [comment]
> FYI this needs to include state_overrides to meet ERC-4337 integration requirements

@franklywatson Can we have a sample JSON-RPC request with this, so we can try it out during development?

**Comment by franklywatson** [comment]
Partner responded with: 

> In general, the requirement is an API the same as Geth: https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtracecall
> We specifically use a Javascript expression in the tracer field here. https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#traceconfig

Attached is a request/response payload example from another chain, however, bear in mind it won't run on Flow given it's for another network
[debug_traceCall with overrides example.txt](https://github.com/user-attachments/files/17194782/debug_traceCall.with.overrides.example.txt)

**Comment by m-Peter** [comment]
Thanks @franklywatson , I have made some working examples of JavaScript tracer with state overrides.

**Comment by dancoombs** [comment]
> FYI this needs to include state_overrides to meet ERC-4337 integration requirements

Just to make sure this isn't forgotten, ERC-4337 also requires `eth_call` to support the same [Geth](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth#eth-call) `ethapi.StateOverride` in the API. Not sure if that is tracked in another ticket but the the application of the state overrides can be shared between the two APIs (`debug_traceCall`/`eth_call`)

**Comment by m-Peter** [comment]
> > FYI this needs to include state_overrides to meet ERC-4337 integration requirements
> 
> Just to make sure this isn't forgotten, ERC-4337 also requires `eth_call` to support the same [Geth](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth#eth-call) `ethapi.StateOverride` in the API. Not sure if that is tracked in another ticket but the the application of the state overrides can be shared between the two APIs (`debug_traceCall`/`eth_call`)

That's a good call out :+1: Currently `eth_call` does not support the `ethapi.StateOverride`, but I'll open up a new issue for it.

**Comment by m-Peter** [comment]
Completed by https://github.com/onflow/flow-evm-gateway/pull/635
