### ISSUE TITLE
Incorporate & implement interface from `offchain` package in `flow-go`

### ISSUE THREAD

**Issue by m-Peter** [onflow/flow-evm-gateway#629]
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-evm-gateway/issues/630
- [ ] https://github.com/onflow/flow-evm-gateway/issues/631
- [ ] https://github.com/onflow/flow-evm-gateway/issues/633
- [ ] https://github.com/onflow/flow-evm-gateway/issues/634
- [ ] https://github.com/onflow/flow-evm-gateway/issues/638
- [ ] https://github.com/onflow/flow-evm-gateway/issues/641
- [ ] https://github.com/onflow/flow-evm-gateway/issues/642
- [ ] https://github.com/onflow/flow-evm-gateway/issues/643
```

**Comment by m-Peter** [comment]
Completed by https://github.com/onflow/flow-evm-gateway/pull/635
